apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-credentials
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgBQHjHib4EDLSXCi/qIzXtTlY0WaGuMT7xRIxUxKi5GNk69w7h/XYRZeVTEzMhJpyOFCRyuUeV7TZxJenjHGB7HSORYP7qh2llJK6x/022PXDkWrgmQkCIIsVWgNNQ0Gs3Cw3QG79jonDphQ70Di5bfbE4/HKZjZrRW7Qg3SmMWhWsgebcE3s5AbtVPV7xnqBaTDc+nW3hrgtMKHoXV92vPioNpbzTtvZJB1GDY845F4WUWKODXc2sZrKWmmtvg0NRNX4GGwj3+rBztjTSv9pyYzlQjdjVZgETy05pxCetDmcbfCNmlCsAN0rdgivgPFdNNULMsK3hAq/L7sA/PsKMppsBxRpj/8IPnRf8vXcOqmSvcbuoIxTv4rKjHQ/azwv4xTxTZAVjJHxgkwktLhmEzohTlybVj4zqIlfbAL4oco2jLTIlg2QLbHgOuzRRQCQUt6myt6046n2Lh9G/lqOqIdRmgzTwP+4CC2F3A/wj8qmIshoKTSveux+K8NWEn/0HaJVMwebrYi0ZurCtRtwkhmKZg9cttirMxotWNLBti/OPH2+Af2Mawg92E6qrWq5KJI8BESFMyJ+gotR0H97L9Su+Rdk8ezQEp1Qq3QWO+dWMXAxrmCUHh34Z2rWNusRAFgB4HSu8NMqG+IFy5C84QNbnWKOuzeiURyITHVpcLWNxDBhLUfV7J4jXV6hlSb3Ttwtp1CLMuBK9VSBlebXqw/WNd5r3YthX5rKGzLHztZR7ZmS3AmDViATsjtoB5P3sJ5qRbXsuwGMDDBNx9kSyD
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-credentials
      namespace: vaultwarden