apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homelable-backend-pvc
  namespace: homelable
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 2Gi