apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-credentials
  namespace: network
spec:
  encryptedData:
    TUNNEL_TOKEN: AgBRMWtGlLqyaNiFF+sYNXO4t4eFWYLXu/9kvzkRwGv8q2N+oYPldglSs30mmyCsnlgi2LBeiig4jAJ1rJwKWrAHOSN2HLr6T2ks+kOToicoKjsblmybqqscmQkRkqvlU8kJ/g/f7sbqck40TnqLK7iWql8xXzQAeciAmsFgkF/NHsrkqvCuHr6SUo+Rx8dYDJd++yotVoNjBTxHFPv8/I00B+NMBkZy4LN25OpcS6PL36qEmyYPRoo6+vTqhwv4gYPUGbsgbkB4ixHGo+GksNQVkRbbNdJ4DDfWcOqrE++eYzw4IUFZkeim7gyL1nJVGz86iySsfke4oXX6+YbhR3GaB/RaHc9zF/c41XepGpHX33cvTDGtUACRWFlwdGmXRuduwwpWJ2PyGb/Gg79BRZsTBMZ6R2bx344TCkQwhaodV+TmkUoJIFLTOhoB3MAd7XVTGS+S8VapjeJiHTJfa7QKhwfRiUn1J6TmFIwuVjq153ZwXGhoKuEtnJraiVQ7j+Y3XGvrFoLAbQ7WTVYXE5Ot3aMfnJm6noU0yo4frT1bl9JV5o48UBjDMc5QIddsyMN+UcdfyV0JaVARIka2/zl/LJHluUWQz+2FhQkVot5K29UvaZP8UZlvjlvQrTwlwcENSM/rFp6xfZemOP22iEwkR4gRhpv1TREWkOa62nvBHbVVrxUO4rghqpBK+gnML/0cy/dEGQ7J/1/T/w5LxJP3l5MCa7nscSsBb1J10RWf6pl8ISzkKu6c5EX6xdh2kG8GtsIuSWBK5bp84PDF2fhbqQn1JMYfdDrwDNuZZs/BNCWjZf85b4ynVn48O+qSzvs0HoyRDCqOD+mPqAJTFpnNGGRmVKLMkEzyxpnyQbF8hXDH5h/XBNGlQArHEN+nu1Mh58aeWjprduDvnek+glyxyTlZIJ0Rb9iECs0kReuTdxpQ0cg=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-credentials
      namespace: network