apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-credentials
  namespace: network
spec:
  encryptedData:
    MONGO_PASSWORD: AgBb2AQimluQH5p0iYyhw8/2br3SnyC95nrmEWQh7r9PdsDnOmgkegFo4MpHdMDgCflbR2jYoe6xm6/UwDCRWVEKJvSrhLiW9vqGioTPQy+Q8mL51juxdVrhE9KjTLLud+nPwhMZORmqvUsR2Ik1Zk0YoXgWQYintnJd1WVawOtPu/Iaj92ZyQv1BVZvk8ILoXikCokB3lD/Cak3gyBoOthinPiEhcPbJia0JSgWoSF/bGAzuHusQsTT6GzNRazcRFLzncW0RD2t8XHUVIhBRonh2nwqu3P7z6U41WWk5DLvmz5IYny8qLpGQXNcsKRZxnEEhChLGJRjOk9yC3R1bU4hoOlhfMSNXkck7cdqKVdcChzrDjhLWMyMTzV9/VmhR57iSy0FVbwKjqzxJj+NFEiNyrpwVQV2/XO/N2htSFfnqz9fQACbwfUcREXKyONtwM+F9sjnOhKpSEYdUhDz/7cTomGDjHorifjuYbxP/KpfawLlCoc3FScO20UcCTj4jGj0EgK93jYm7hyTZdW23Ko1HthUo3rsZAmHxZ5faEmCERIR/g1X6ELfjDsdxOwyj99LJAm+rdBUx12KcZZ83pFnqoonWR24a1wSTcQ5RtqzVvTiG7JDPVYmg+hUa7O+G8kSltMAT0xr48ZFn5YQPGPH6+QUk2FTuoNu3BUka8xCTF0APiYGsQiWE4mcORQM+NjG/VeYYu+K1H1cHhw=
  template:
    metadata:
      creationTimestamp: null
      name: mongo-credentials
      namespace: network