apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  services.yaml: |
    - Infrastructure:
        - ArgoCD:
            href: https://192.168.8.100:30944
            description: GitOps
    - Media:
        - Immich:
            href: http://192.168.8.100:31011
            description: Photo backup
  settings.yaml: |
    title: HomeOps
  bookmarks.yaml: ""
  widgets.yaml: ""