apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  services.yaml: |
    - Infrastructure:
        - ArgoCD:
            href: http://192.168.8.100:8080
            description: GitOps
  settings.yaml: |
    title: HomeOps
  bookmarks.yaml: ""
  widgets.yaml: ""